//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlQuery.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sqlQuery.Resources.MyRes", typeof(MyRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据库服务器信息！ 的本地化字符串。
        /// </summary>
        internal static string Err_DBHost {
            get {
                return ResourceManager.GetString("Err_DBHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询语句不合法！ 的本地化字符串。
        /// </summary>
        internal static string Err_QueryInvalid {
            get {
                return ResourceManager.GetString("Err_QueryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名是必须的！ 的本地化字符串。
        /// </summary>
        internal static string Err_Username {
            get {
                return ResourceManager.GetString("Err_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码失败，如果程序安装是到C盘的话，需要以管理员权限来运行。 的本地化字符串。
        /// </summary>
        internal static string Err_WritePriv {
            get {
                return ResourceManager.GetString("Err_WritePriv", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBannner {
            get {
                object obj = ResourceManager.GetObject("imgBannner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        internal static string TXT_ALL_COL {
            get {
                return ResourceManager.GetString("TXT_ALL_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有表 的本地化字符串。
        /// </summary>
        internal static string TXT_ALL_TABLE {
            get {
                return ResourceManager.GetString("TXT_ALL_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlServer连接器 的本地化字符串。
        /// </summary>
        internal static string TXT_APP {
            get {
                return ResourceManager.GetString("TXT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL Server Management Studio 的本地化字符串。
        /// </summary>
        internal static string TXT_APP_TITLE {
            get {
                return ResourceManager.GetString("TXT_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        internal static string TXT_CHK_SAVEPASSWORD {
            get {
                return ResourceManager.GetString("TXT_CHK_SAVEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string TXT_QUERY {
            get {
                return ResourceManager.GetString("TXT_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sql Server服务器： 的本地化字符串。
        /// </summary>
        internal static string TXT_SQL_HOST {
            get {
                return ResourceManager.GetString("TXT_SQL_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录密码： 的本地化字符串。
        /// </summary>
        internal static string TXT_SQL_PASSWORD {
            get {
                return ResourceManager.GetString("TXT_SQL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户名： 的本地化字符串。
        /// </summary>
        internal static string TXT_SQL_USER {
            get {
                return ResourceManager.GetString("TXT_SQL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库 的本地化字符串。
        /// </summary>
        internal static string TXT_TREE_ROOT {
            get {
                return ResourceManager.GetString("TXT_TREE_ROOT", resourceCulture);
            }
        }
    }
}
